### PR TITLE
Fix overriding TTF external font config

### LINKED ISSUE #41: System fonts
I have a problem with prawn-svg adding system fonts to the font registry.
It's hard to come up with a short description of the problem. Sorry.

So I have defined a few fonts in my script like this:
```ruby
doc.font_families.update(
  "Open Sans" => {
    :normal => File.expand_path(File.join(__FILE__, '..', 'assets', 'fonts', 'OpenSans-bold.ttf')),
    :bold => File.join(__FILE__, '..', 'assets', 'fonts', 'OpenSans-extrabold.ttf'),
  }
)
```

Note a few things about the above code:
* I refer to the font by it's real name
* I assign different weights than font designer initially intended. This is governed by the page design. To omit specifying font weigh in every `doc.font` call I use different font for `:normal` font.
* I use TTF version of the font as Prawn currently doesn't support OTF

In addition to that I have OTF version of Open Sans installed in the system.

So the problem is after I define my fonts and use prawn-svg my definitions are getting overridden by system-wide installed fonts. Moreover, prawn-svg overrides my fonts with unusable OTF-variants.

Right now I have a hacked version of prawn-svg to work around this problem. My solution is to use `'svg:'` prefix in all font-names added/used by prawn-svg.

I don't provide a pull request as I think it's a sub-par solution for a number of reasons.
* It still adds all system fonts to the registry. It gets polluted with a lot of unused fonts.
* It add unusable fonts to the registry.

I think the right solution would be the following:

* When prawn-svg detects a font being used it should check if the font and weight is already in the font registry
* If it is we're done. Use whatever is in there.
* If it's not, search in system fonts for a usable version (TTF/DFont/AFM) of what we need and register it in the font registry. Also produce a warning of a missing font/style and that a specific system font is being used.
* If font is not found anywhere, produce a warning of a missing font/style and use fallback font.

### PR DESCRIPTION
**Pull request by isaacseymour**
Closes #41 

I tried to write a failing spec but I'm not entirely sure I understand what this method does in the first place.

### CODE REVIEW

**Comment by isaacseymour** [comment]
Hi @mogest would you be able to have a look at this this week? We're having to run off this branch of `prawn-svg` until this is released, and I'd much rather be on the official Rubygems version!

**Comment by mogest** [comment]
Should be able to look at it tomorrow.  Thanks.

**Comment by isaacseymour** [comment]
Sorry to hassle @mogest - would you be able to take a look soon?

**Comment by mogest** [comment]
I've been holding this up due to waiting for a prawn release; I don't think that's coming so good to go now.  Thanks for the contribution!

**Pull request merged**
