### PR TITLE
resolves #82 fix crash calculating font subfamily name

### LINKED ISSUE #82: Exception thrown if SVG contains italic text
If the SVG includes text that has the font-style CSS property set to italic, Prawn SVG crashes. The crash occurs when Prawn attempts to invoke the `strip` method on a symbol.

Here's the problematic code in lib/prawn/svg/font.rb

```ruby
  def subfamily_name
    sfn = if weight == :normal && style
      style
    elsif weight || style
      "#{weight} #{style}"
    else
      "normal"
    end

    sfn.strip.gsub(/\s+/, "_").downcase.to_sym
  end
```

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Nope, that's not necessary. The join method converts each element to a string before joining them. See http://ruby-doc.org/core-2.3.0/Array.html#method-i-join

**Comment by mojavelinux** [comment]
@mogest would you be willing to do a release shortly after merging this PR? I think that diagramming tools used by Asciidoctor Diagram frequently use italic text, so I'm starting to get hit with a lot of support requests that stem from this bug.

**Comment by mojavelinux** [comment]
...and I'm just about to release a new version of Asciidoctor PDF.

**Comment by mogest** [comment]
Sure thing.  Thanks!

**Pull request merged**
